# All inputs and constants are automatically also set to terminals as
# they have 0 arity. Variables are read from the fitness case file
arities:
    "+": 2
    "*": 2
    "/": 2
    "-": 2

# Specify the constants you would like to employ in your evaluation
# the program will use 0 to the number you specified
constants:
    - 0
    - 1

# Specify the number of individuals(population) make sure the
# population size is GREATER than the number of inputs
population_size: 4

# Specify the max depth of the tree
max_depth: 3

# Specify the number of best individuals that are preserved between generations
elite_size: 1

# Specify the number of generations you would like to generate
generations: 30

# Specify the number of individual solutions that are compared when
# determining which solutions are inserted into next generation of the
# search loop
tournament_size: 3

# Random seed. Enables a user to replicate experiment
seed: 0

# Probability of individual solutions to be varied by the crossover operator
crossover_probability: 0.9

# Probability of individual solutions to be varied by the mutation operator
mutation_probability: 0.1

# Name of file that has data(inputs and outputs) stored in it.
fitness_cases: "fitness_cases.csv"

# Ratio of fitness cases used for trainging individual solutions
test_train_split: 0.7